[package]
name = "dj-rs"
version = "0.1.0"
authors = ["Jonas Liljestrand <jonas.liljestrand@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "^0"
once_cell = "1"
waveform = "0.3.2"
gdk-pixbuf = "0.15.11"
gstreamer-audio = "0.18.7"
gstreamer = "0.18.8"
anyhow = "*"

[dependencies.gtk4]
version = "0.4.8"

[dependencies.gio]
version = "0.15.11"
features = ["v2_72"]
